backend/app/controllers/module.controller.js, backend/app/routes/module.route.js, backend/app/services/module.services.js, backend/app/validators/module.validator.js, backend/migrations/20250302025605-create-module-table.js, backend/models/binnacle.js, backend/models/blacklist.js, backend/models/farm.js, backend/models/farm_user.js, backend/models/hardware.js, backend/models/module.js, backend/models/module_user.js, backend/models/notification.js, backend/models/parameter.js, backend/models/report.js, backend/models/rol.js, backend/models/sensor.js, backend/models/threshold.js, backend/models/user.js, backend/seeders/20250303095830-demo-modules.js, backend/server.js, test-resources/modules.postman_collection.json
=> AQ-15 List Modules

backend/package-lock.json, package-lock.json, test-resources/user.postman_collection.json
[AQ-15](https://aquaterra-sena.atlassian.net/browse/AQ-15?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
// 
//
//
=> AQ-15 register user

backend/app/controllers/farm.controller.js, backend/app/routes/farm.route.js, backend/app/services/farm.services.js, backend/app/utils/apiResponse.js, backend/app/validators/farm.validator.js
[AQ-52](https://aquaterra-sena.atlassian.net/browse/AQ-52)
Implements pagination en farm list endpoint.
//
=> AQ-52 adds the logic necessary to paginate farms.

backend/app/controllers/farm.controller.js, backend/app/controllers/module.controller.js, backend/app/routes/farm.route.js, backend/app/routes/module.route.js, backend/app/services/farm.services.js, backend/app/services/module.services.js, backend/app/utils/apiResponse.js, backend/app/validators/farm.validator.js, backend/app/validators/module.validator.js, docs/pull_request_template.md
[AQ-53](https://aquaterra-sena.atlassian.net/browse/AQ-53)
Adds the pagination for the modules
//
=> AQ-53 implements pagination in modules

backend/package-lock.json, backend/package.json, package-lock.json
[AQ-54](https://aquaterra-sena.atlassian.net/browse/AQ-54)
Update outdate packages
//
=> AQ-54 Update outdated packages

backend/app/controllers/shared/user.controller.js, backend/app/routes/shared/user.route.js, backend/app/services/shared/user.service.js, backend/app/validators/shared/user.validator.js, test-resources/new_backend_acuaterra_postman.postman_collection.json
[AQ-31](https://aquaterra-sena.atlassian.net/browse/AQ-31)
Add a list so that the application administrator can see all the data of the users registered in the database, meeting the acceptance criteria.
=> AQ-31 List Users

backend/migrations/20250308134142-change-farm-coordinates-to-float.js, backend/models/farm.js
[AQ-40](https://aquaterra-sena.atlassian.net/browse/AQ-40)
I corrected the model data that did not match the acceptance criteria
=> AQ-40 Register Farms corrected model

backend/app/middleware/validateUserCreation.middleware.js, backend/app/routes/shared/user.route.js, backend/app/validators/shared/user.validator.js
[AQ-40](https://aquaterra-sena.atlassian.net/browse/AQ-40)
I corrected the user.validator so that you receive only integer and id_rol integer
=> AQ-40 Regsiter User Correction

backend/app/services/shared/user.service.js, backend/app/validators/shared/user.validator.js, backend/migrations/20250311062213-add-contact-to-users.js, backend/models/user.js, backend/seeders/20250302043502-demo-users.js
[AQ-15](https://aquaterra-sena.atlassian.net/browse/AQ-40?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
I corrected the contact field of the user table and the model with a migration, so the service, the controller and the validator had to be modified where required.
=> AQ 40 Register User Correction Add Phone

backend/app/controllers/shared/auth.controller.js
[AQ-40](https://aquaterra-sena.atlassian.net/browse/AQ-40?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
I corrected error login
=> AQ-40 Register Correction error login

backend/app/controllers/shared/user.controller.js, backend/app/middleware/validateUserUpdate.middleware.js, backend/app/routes/admin/user.admin.route.js, backend/app/routes/shared/user.route.js, backend/app/services/shared/user.service.js, backend/app/swagger/paths/shared/users/edit_user.json, test-resources/user.postman_collection.json
[AQ-33](https://aquaterra-sena.atlassian.net/browse/AQ-33?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Add the module that allows editing a user created by the admin and the owner.
Add role validator logic for the PUT route, leaving all fields editable.
=> AQ 33 User Edit

backend/app/controllers/owner/module.owner.controller.js, backend/app/middleware/validateModuleCreate.middleware.js, backend/app/middleware/validateModuleUpdate.middleware.js, backend/app/routes/owner/module.owner.route.js, backend/app/services/owner/module.owner.services.js, backend/app/swagger/paths/owner/put_modules.json, backend/app/validators/owner/module.owner.validator.js, backend/models/module.js, backend/models/user.js, test-resources/modules.postman_collection.json
[AQ-47](https://aquaterra-sena.atlassian.net/browse/AQ-47?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Perform the service so that an owner can update his correctly created module with its due permissions and restrictions, we added documentation and Postman collection
// 
**Login  con id rol = 1 (Admin)**
**Login con id rol =  2(Owner)**
Payload
User and assigned farm relationship table
**Accessing to update a farm that is not assigned to the owner with id 19**
**Users assigned to the module with id that are admin and owner role**
=> AQ-47 Upgrade module

backend/seeders/20250321234745-seed-new-users-admin.js
[AQ-15](https://aquaterra-sena.atlassian.net/browse/AQ-114?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
// add seeder user admin
//
=> AQ- 114 Add seeder user admin

backend/app/controllers/owner/module.owner.controller.js, backend/app/middleware/validateModuleDelete.middleware.js, backend/app/routes/owner/module.owner.route.js, backend/app/services/owner/module.owner.services.js, backend/app/swagger/paths/owner/delete-module-swagger.json, backend/migrations/20250322152952-add-column-deleteat-module-threshold-measurement-sensor.js, backend/models/measurement.js, backend/models/module.js, backend/models/sensor.js, backend/models/threshold.js, test-resources/modules.postman_collection.json
[AQ-49](https://aquaterra-sena.atlassian.net/browse/AQ-49?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Add the complete module for the delete method of modules, with its Swagger documentation and we add the Postman collection with this endpoint.
=> AQ 49 Delete module

backend/app/controllers/owner/module.owner.controller.js, backend/app/middleware/validateModuleAccess.middleware.js, backend/app/routes/owner/module.owner.route.js, backend/app/services/owner/module.owner.services.js, backend/app/swagger/paths/owner/get_module.json, test-resources/modules.postman_collection.json
[AQ-48](https://aquaterra-sena.atlassian.net/browse/AQ-48?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Add the full module by viewing the module ID, add Swagger documentation, and update the Postman collection.
=> AQ -48 Show module

backend/app/enums/roles.enum.js, backend/app/middleware/validateModuleCreate.middleware.js, backend/app/services/owner/module.owner.services.js, backend/app/swagger/paths/owner/post_modules.json, backend/app/views/emails/new_sensor.ejs, backend/migrations/20250323204636-add-rol-4-sensor.js, backend/migrations/20250324023820-role-correction.js, backend/package-lock.json, backend/package.json
[AQ-129](https://aquaterra-sena.atlassian.net/browse/AQ-129?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Implement the creation of the sensor user in the creation of the module along with the email that should reach the owner
=> AQ-129 automatic creation sensor user

backend/app/middleware/validateModuleShow.middleware.js, backend/app/routes/owner/module.owner.route.js, backend/app/services/owner/module.owner.services.js
[AQ-132](https://aquaterra-sena.atlassian.net/browse/AQ-132?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
fix the view module middleware and the view module response
=> AQ-132 Fix middleware file view module

backend/migrations/20250325043822-changue-column-module-user-table.js, backend/models/module.js, backend/models/module_user.js, backend/models/user.js
[AQ-133](https://aquaterra-sena.atlassian.net/browse/AQ-15?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
I fixed the id_person column to id_user in the module_user table, the code was reviewed so that everything is working
=> AQ- 133 Change column module user table

backend/app/controllers/module/measurement.controller.js, backend/app/routes/module/measurement.route.js, backend/app/services/module/measurement.service.js, backend/app/swagger/paths/module/swagger-measurement.json, test-resources/measurements.postman_collection.json
[AQ-136](https://aquaterra-sena.atlassian.net/browse/AQ-136?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Add the module to list the measurement data, with its documentation and Postman collection.
=> AQ-136 - Listar datos de muestras del sensor

backend/app/controllers/module/measurement.controller.js, backend/app/middleware/validateSensorThreshold.middleware.js, backend/app/middleware/validateUserCreation.middleware.js, backend/app/routes/module/measurement.route.js, backend/app/services/module/measurement.service.js, backend/app/services/notifications/notification.factory.js, backend/app/services/notifications/sensor-alert-handler.service.js, backend/app/services/notifications/sensor-alert-notification.js, backend/app/swagger/paths/module/swagger-measurement.json, backend/app/utils/based.threshold.js
[AQ-137](https://aquaterra-sena.atlassian.net/browse/AQ-137?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
adjust the based.threshold.js file so that the thresholds can be obtained through two methods that verify the sensor type and obtain the maximum and minimum threshold, adjust measurement.controller.js, in its create and list method, in the route the middleware that is validating the measurements was added, adjust the measurement service, add the sensor-alert-handler.service.js file, which is the handler of the notification alerts, sensor-alert-notification.js is the file that extends baseNotification.js and the validator of the measurement route
=> AQ-137 Validate measurement data

backend/app/services/notifications/sensor-alert-handler.service.js
[AQ-140(https://aquaterra-sena.atlassian.net/browse/AQ-140?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Correction od errors
=> AQ-140 Correction of errors

backend/app/services/notifications/sensor-alert-handler.service.js
[AQ-140](https://aquaterra-sena.atlassian.net/browse/AQ-140?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Correction of errors 2.0
=> AQ-140 Correction of errors 2.0

backend/app/controllers/owner/user.owner.controller.js, backend/app/middleware/validateMonitorDisable.middleware.js, backend/app/routes/owner/user.owner.route.js, backend/app/services/owner/user.owner.service.js, backend/app/swagger/paths/owner/delete-monitor.json, test-resources/user.postman_collection.json
[AQ-150](https://aquaterra-sena.atlassian.net/browse/AQ-150?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Implement softDelete to make inactive the monitor users that need to be deleted, with its MVC and its respective middleware. Attached is documentation of Swagger plus updated Postman collection with the delete method.
=> AQ-150 Implement softDelete to make inactive the monitor users

backend/app/controllers/shared/auth.controller.js, backend/app/routes/auth.route.js, backend/app/services/shared/auth.service.js, backend/app/swagger/paths/shared/auth/change-password.json, backend/app/swagger/paths/shared/auth/login.json, backend/app/validators/shared/auth.validator.js, backend/migrations/20250410205354-add-must-change-password-user.js, backend/models/user.js, docs/AUTH_README.md, test-resources/auth.postman_collection.json
[AQ-37](https://aquaterra-sena.atlassian.net/browse/AQ-37?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
The complete temporary password management system has been implemented with the following features:
Added a mustChangePassword field to the User model.
Implemented the /change-password endpoint for temporary password changes.
Improved the login response to include the mustChangePassword flag.
Added security validations for new passwords.
Implemented detailed documentation in AUTH_README.md.
Added updated Swagger documentation and Postman collection.
=> Feature/aq 37 Temporary password change

backend/app/swagger/paths/shared/auth/login.json
[AQ-37](https://aquaterra-sena.atlassian.net/browse/AQ-37?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Correction documentation swagger
=> AQ-37 Correction documentation swagger

backend/app/controllers/owner/user.owner.controller.js, backend/app/middleware/validateModuleAccess.middleware.js, backend/app/middleware/validateMonitorDisable.middleware.js, backend/app/middleware/validateUserMonitorCreation.middleware.js, backend/app/middleware/validateUserMonitorUpdate.middleware.js, backend/app/routes/owner/user.owner.route.js, backend/app/services/owner/user.owner.service.js, backend/app/swagger/paths/owner/create.monitor.json, backend/app/swagger/paths/owner/delete-monitor.json, backend/app/swagger/paths/owner/get_list_monitor_asociate_module.json, backend/app/swagger/paths/owner/update.monitor.json, backend/migrations/20250412022028-update-user-role-to-monitor.js
[AQ-155](https://aquaterra-sena.atlassian.net/browse/AQ-155?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
I corrected the service, controller, middlewares and route adjusting it to queries related to module users since it was failing when making queries directly from users to farms, I corrected documentation since the complete CRUD was included, I made a migration correcting the user role per monitor in the database
=> AQ-155 Bug fixes owner role user management service

backend/app/services/shared/threshold.shared.service.js, backend/app/validators/owner/module.owner.validator.js
[AQ-46](https://aquaterra-sena.atlassian.net/browse/AQ-46?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
I fixed the error when creating the module that was not creating the threshold service and was allowing the module names to be repeated.
=> AQ-46 Fixed the error when creating the module 

backend/app/middleware/validateModuleShow.middleware.js
[AQ-48](https://aquaterra-sena.atlassian.net/browse/AQ-48?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Fix module not found response with current status of 403 which should be 404
=> AQ-48 Fix error view module

backend/app/controllers/shared/auth.controller.js, backend/app/routes/auth.route.js, backend/app/services/shared/auth.service.js, backend/app/swagger/paths/shared/auth/request-password-reset.json, backend/app/swagger/paths/shared/auth/reset-password.json, backend/app/validators/shared/auth.validator.js, backend/app/views/emails/password_reset.ejs, test-resources/auth.postman_collection.json
[AQ-44](https://aquaterra-sena.atlassian.net/browse/AQ-44?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
I implemented the complete services for restoring lost passwords through two endpoints: one that requests the change and the other that generates the change with their respective input data validators. I added their respective ejs file for the sent email. Detailed documentation for both services was added, plus the updated Postman collection.
=> AQ-44 Password restaured

backend/app/middleware/validateUserMonitorCreation.middleware.js, backend/app/services/owner/user.owner.service.js, backend/app/swagger/paths/owner/create.monitor.json, test-resources/user.postman_collection.json
[AQ-158](https://aquaterra-sena.atlassian.net/browse/AQ-158?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Modify the monitor log so that it is created without relation to the module, fix its documentation and updated Postman collection.
=> AQ-158 Modification user registry monitor

backend/app/controllers/owner/module.owner.controller.js, backend/app/middleware/validateModuleMonitorAssignment.middleware.js, backend/app/routes/owner/module.owner.route.js, backend/app/services/owner/module.owner.services.js, backend/app/swagger/paths/owner/module.monitor.assignment.json, test-resources/modules.postman_collection.json
Link Jira
[AQ-159](https://aquaterra-sena.atlassian.net/browse/AQ-159?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Description
Create an MVC with the service to be able to assign a user to a specific module. It has its respective middleware and Swagger documentation. Update the Postman collection.
New Environments
Screenshots
=> AQ-159 Create user module relations

backend/app/middleware/validateUserMonitorUpdate.middleware.js, backend/app/services/owner/user.owner.service.js, backend/app/swagger/paths/owner/update.monitor.json, backend/app/validators/owner/monitor.owner.validator.js, test-resources/user.postman_collection.json
Link Jira
[AQ-161](https://aquaterra-sena.atlassian.net/browse/AQ-161?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Description
Edit the edit user monitor service by owner, removing all logic related to modules since it is not assigning these relationships through this edit service. This meant that the validator and its respective middleware had to be modified. We corrected the documentation and updated the Postman collection.
New Environments
Screenshots
=> AQ-161 Edit the edit user monitor service 

backend/app/controllers/owner/user.owner.controller.js, backend/app/middleware/validateMonitorReactivate.middleware.js, backend/app/routes/owner/user.owner.route.js, backend/app/services/owner/user.owner.service.js, backend/app/swagger/paths/owner/reactive-monitor.json, test-resources/user.postman_collection.json
[AQ-162](https://aquaterra-sena.atlassian.net/browse/AQ-162?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Create the complete service to reactivate monitor users by the owner with its respective MVC and middleware, we added Swagger documentation, we updated Postman collection
=> AQ-162 Activating monitors state

backend/app/controllers/owner/module.owner.controller.js, backend/app/middleware/validateModuleMonitorAssignment.middleware.js, backend/app/routes/owner/module.owner.route.js, backend/app/services/owner/module.owner.services.js, backend/app/swagger/paths/owner/module.monitor.assignment.json, test-resources/modules.postman_collection.json
[AQ-164](https://aquaterra-sena.atlassian.net/browse/AQ-164?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Modify the monitor-to-module assignment service so that it can receive an array of monitor IDs to assign to the specific module. The controller service, middleware route, documentation, and Postman collection were modified.
=> AQ-164 Modify implementation assigning monitors module

backend/app/services/owner/module.owner.services.js, backend/app/swagger/paths/owner/module.monitor.assignment.unassign.json, test-resources/modules.postman_collection.json
[AQ-165](https://aquaterra-sena.atlassian.net/browse/AQ-165?atlOrigin=eyJpIjoiOWE0ZWQ2MmY1ZGJjNGIxN2JjNDhhYWFlYzU0MTI1YWIiLCJwIjoiaiJ9)
Implementation of module monitor designation, attached updated Swagger documentation and updated Postman collection
=> Aq-165 Immplementing module monitor designation
